services:
  samba:
    build:
      context: ./dockerfile
      target: dc
    container_name: ${DC_NAME}
    dns:
      - ${DC_IP}
      - ${MAIN_DNS_IP}
    dns_search:
      - ${DOMAIN_FQDN}
    environment:
      - DOMAIN_FQDN=${DOMAIN_FQDN}
      - DOMAIN_DN=${DOMAIN_DN}
      - DNSFORWARDER=${MAIN_DNS_IP}
      - DC_IP=${DC_IP}
    extra_hosts:
      - ${DC_NAME}.${DOMAIN_FQDN}:${DC_IP}
      - ${DCb_NAME}:${DCb_IP}
      - ${DCb_NAME}.${DOMAIN_FQDN}:${DCb_IP}
      - ${DCc_NAME}:${DCc_IP}
      - ${DCc_NAME}.${DOMAIN_FQDN}:${DCc_IP}
      - ${DCd_NAME}:${DCd_IP}
      - ${DCd_NAME}.${DOMAIN_FQDN}:${DCd_IP}
    hostname: ${DC_NAME}
    networks:
      intranet:
        ipv4_address: ${DC_IP}
    privileged: true                                  # Run as true root. Required on a DC because the vfs_acl_xattr module is enabled automatically, which uses the security.* namespace (see https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html).
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/etc/samba/config
      - data:/var/lib/samba

networks:
  intranet:
    attachable: true
    driver: macvlan
    driver_opts:
      parent: ${HOST_INTERFACE}
    ipam:
      config:
        - subnet: "${SUBNET}"                         # Shared with the host
          gateway: "${GATEWAY}"                       # Same as on the host
    name: intranet

volumes:
  config:
    driver: local
  data:
    driver: local
