services:

  samba:
    container_name: samba
    hostname: ${DC_NAME}
    build: ./dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/samba/config
      - ./data:/var/lib/samba
    environment:
      - DOMAIN_FQDN=${DOMAIN_FQDN}
      - DOMAIN_DN=${DOMAIN_DN}
      - DNSFORWARDER=${MAIN_DNS_IP}
      - DC_IP=${DC_IP}
    dns_search:
      - ${DOMAIN_FQDN}
    dns:
      - ${DC_IP}
      - ${MAIN_DNS_IP}
    extra_hosts:
      - ${DC_NAME}.${DOMAIN_FQDN}:${DC_IP}
    privileged: true                                  # Run as true root. Required by Samba because it uses the security.* namespace (see https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html).
    networks:
      sambanet:
        ipv4_address: ${DC_IP}

networks:
  sambanet:
    driver: macvlan
    driver_opts:
      parent: ${HOST_INTERFACE}
    ipam:
      config:
        - subnet: "${DC_SUBNET}"                      # Shared with the host
          gateway: "${DC_GATEWAY}"                    # Same as on the host
          ip_range: "${DC_IP}/32"                     # Tell Docker which IP addresses are available for containers
